
import { NicheConfig, NicheType } from './types';

export const NICHE_CONFIGS: Record<NicheType, NicheConfig> = {
  legal: {
    id: 'legal',
    label: 'Legal / Law Firm',
    icon: '⚖️',
    color: 'text-blue-400',
    bgColor: 'bg-blue-500/10',
    borderColor: 'border-blue-500/30',
    description: 'Law firms, attorneys, paralegals',
    tone: 'Serious, calm, empathetic, and professional.',
    callFlow: [
      'Greet caller warmly and professionally',
      'Identify what type of legal matter they need help with',
      'Ask for their name and preferred callback number',
      'Determine urgency (hearing, deadline, or emergency)',
      'Offer to schedule a free consultation',
      'Confirm appointment details',
    ],
    qualificationQuestions: [
      'What type of legal issue brings you to us today?',
      'Have you worked with an attorney on this before?',
      'Is this matter time-sensitive?',
      'Are you seeking representation or just a consultation?',
    ],
    bookingBehavior: 'Schedule a free 15-minute consultation.',
    sampleGreeting: 'Thank you for calling. How can I assist you today?',
    roiConfig: { avgMissedCallsPerMonth: 45, avgRevenuePerLead: 2500, hoursPerMonth: 60, closingRate: 0.35 },
    promptLayer: 'INDUSTRY: Legal / Law Firm. TONE: Serious, calm, professional. Never give legal advice. Offer free consultation. Capture name and phone. Ask about urgency and case type.',
  },
  beauty: {
    id: 'beauty',
    label: 'Beauty & Aesthetics',
    icon: '💅',
    color: 'text-pink-400',
    bgColor: 'bg-pink-500/10',
    borderColor: 'border-pink-500/30',
    description: 'Med spa, hair salon, barber, nails, aesthetics',
    tone: 'Friendly, upbeat, warm, and enthusiastic.',
    callFlow: [
      'Greet with warm, upbeat energy',
      'Ask what service they are looking for',
      'Mention current promotions or popular services',
      'Check availability for their preferred date/time',
      'Collect name, phone, and service details',
      'Confirm booking and send reminder',
    ],
    qualificationQuestions: [
      'What service are you looking to book today?',
      'Is this your first time visiting us?',
      'Do you have a preferred stylist?',
      'What days and times work best?',
    ],
    bookingBehavior: 'Book appointments directly. Mention current promotions.',
    sampleGreeting: 'Hey, thanks so much for calling! How can I help you today?',
    roiConfig: { avgMissedCallsPerMonth: 80, avgRevenuePerLead: 150, hoursPerMonth: 40, closingRate: 0.70 },
    promptLayer: 'INDUSTRY: Beauty & Aesthetics. TONE: Warm, upbeat, friendly. Book appointments. Ask about service, preferred day/time. Capture name and phone. Mention any specials.',
  },
  healthcare: {
    id: 'healthcare',
    label: 'Healthcare',
    icon: '🏥',
    color: 'text-cyan-400',
    bgColor: 'bg-cyan-500/10',
    borderColor: 'border-cyan-500/30',
    description: 'Dental, chiropractic, physical therapy, medical',
    tone: 'Caring, structured, patient, and reassuring.',
    callFlow: [
      'Greet caller and verify you reached the right practice',
      'Ask if they are a new or existing patient',
      'Identify the reason for the visit',
      'Check insurance preference',
      'Schedule appointment at preferred time',
      'Collect patient info and send confirmation',
    ],
    qualificationQuestions: [
      'Are you a new or existing patient?',
      'What brings you in today?',
      'Are you experiencing any pain?',
      'Do you have health insurance?',
    ],
    bookingBehavior: 'Schedule patient appointments. Handle emergencies with urgency.',
    sampleGreeting: 'Thank you for calling. How can I help you today?',
    roiConfig: { avgMissedCallsPerMonth: 60, avgRevenuePerLead: 400, hoursPerMonth: 50, closingRate: 0.60 },
    promptLayer: 'INDUSTRY: Healthcare. TONE: Caring, calm, patient. Never give medical advice. For pain or emergency, prioritize urgency. Check insurance. Capture name, DOB if existing patient.',
  },
  home_services: {
    id: 'home_services',
    label: 'Home Services',
    icon: '🏡',
    color: 'text-orange-400',
    bgColor: 'bg-orange-500/10',
    borderColor: 'border-orange-500/30',
    description: 'Landscaping, lawn care, plumbing, HVAC, cleaning',
    tone: 'Direct, efficient, friendly, and confident.',
    callFlow: [
      'Quick, professional greeting',
      'Ask what service they need',
      'Get their address and property type',
      'Determine one-time or recurring service',
      'Schedule a quote visit or direct booking',
      'Collect contact info and send confirmation',
    ],
    qualificationQuestions: [
      'What service do you need help with?',
      'What is the address?',
      'Is this a one-time or recurring service?',
      'When would you need us?',
    ],
    bookingBehavior: 'Schedule estimates or direct bookings. Get address and job details.',
    sampleGreeting: 'Hey, thanks for calling! What can we help you with?',
    roiConfig: { avgMissedCallsPerMonth: 70, avgRevenuePerLead: 350, hoursPerMonth: 45, closingRate: 0.55 },
    promptLayer: 'INDUSTRY: Home Services. TONE: Direct, friendly, efficient. Get service type and address. One-time or recurring? Schedule same-week if possible. Offer free estimates for large jobs.',
  },
  financial: {
    id: 'financial',
    label: 'Financial Services',
    icon: '💰',
    color: 'text-yellow-400',
    bgColor: 'bg-yellow-500/10',
    borderColor: 'border-yellow-500/30',
    description: 'Tax prep, accounting, bookkeeping, financial planning',
    tone: 'Professional, trustworthy, composed, and knowledgeable.',
    callFlow: [
      'Professional greeting with firm name',
      'Identify the service they are looking for',
      'Determine if new or returning client',
      'Understand their situation (individual, LLC, etc)',
      'Schedule a free initial consultation',
      'Collect contact info and send intake form',
    ],
    qualificationQuestions: [
      'Personal or business taxes, or both?',
      'New or returning client?',
      'Individual, LLC, S-Corp, or C-Corp?',
      'Do you have a specific deadline?',
    ],
    bookingBehavior: 'Schedule a free consultation. Understand client type before booking.',
    sampleGreeting: 'Thank you for calling. How can I assist you today?',
    roiConfig: { avgMissedCallsPerMonth: 40, avgRevenuePerLead: 800, hoursPerMonth: 55, closingRate: 0.45 },
    promptLayer: 'INDUSTRY: Financial Services. TONE: Professional, trustworthy. Never quote specific fees. Schedule free consultation. Determine entity type. Capture name, email, phone.',
  },
};

export function getNicheConfig(niche: NicheType): NicheConfig {
  return NICHE_CONFIGS[niche];
}

export function getAllNiches(): NicheConfig[] {
  return Object.values(NICHE_CONFIGS);
}
